# Generated by Django 3.1 on 2020-08-11 17:03

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to=ecommerce.models.cat_upload_directory)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to=ecommerce.models.product_upload_directory)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('categories', models.ManyToManyField(to='ecommerce.Category')),
            ],
        ),
    ]
